
services:
  wallet-service:
    build:
      context: ./wallet_service
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - database
    volumes:
      - ./wallet_service:/app
    restart: always

  database:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  kafka-ui:
      image: provectuslabs/kafka-ui:latest
      ports:
        - "9099:8080"
      environment:
        KAFKA_CLUSTERS_0_NAME: kafka-cluster
        KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 157.66.218.191:9092
        KAFKA_CLUSTERS_0_ZOOKEEPER: 157.66.218.191:2181
        KAFKA_CLUSTERS_0_SCHEMAREGISTRY: 157.66.218.191:8081
        DYNAMIC_CONFIG_ENABLED: 'true'

volumes:
  postgres_data:

